#!/bin/bash

####
## attach - Join a previously started tmux session
## usage: attach <Optional<session_id>>
####

attach() {
  if type "tmux" > /dev/null; then

    local SESSION=$1

    # TODO should I convert to unix code \e[00m or use tput?
    local readonly GREEN=$(tput setaf 2)
    local readonly NORMAL=$(tput sgr0)

    # if no properties passed to function
    if [ $# -eq 0 ]; then

      # test if tmux is running
      tmux ls >> /dev/null 2>&1
      if [ $? -eq 0 ]; then
        printf "${GREEN}list:________\n${NORMAL}";
        tmux ls -F '#{session_name}'
        printf "\n\nWhat session would you like to attach? " -n
        read SESSION
        $(tmux attach -d -t $SESSION)
      else
        printf "${GREEN}No sessions created\n${NORMAL}"
        read -t 1 -p "starting tmux ... | press ANY key to cancel" || tmux
      fi

    else
      if [ $? -ne 0 ]; then
        $(tmux attach -d -t $SESSION)
      else
        printf "ERR: Could not find session \`${SESSION}\`\n"
      fi
    fi
  fi
}

