#!/bin/bash

function _usage() {
    echo -e " Usage: NRVault <Options> <Command>

    Options:
      -h                      ......  Prints this Menu
      -r <region>             ......  Set Region, Defaults to 'us'
      -v                      ......  Messages will be verbose
      -cc|--check-connection  ......  Check Connection

    Commands:
      ls <vault-path>     ...... Displays a List of values for vault-path
      write <vault-path> <key> <value> .... Writes to vault and saves the data to the supplied vault-path
      delete <vault-path> .... [uninstrumented] removes item from vault and saves the data to the supplied vault-path
    "

    echo -e "set ENV variable NRV_DEBUG show messages"
}

function _setVaultData() {
  method=$1
  vault_path=$2
  k=$3
  v=$4
  default_region="us"
  region="${NRV_REGION:-$default_region}"

  if [[ $NRV_DEBUG ]]; then
    echo {path:$vault_path, region: $region, kv: $kv}
  fi

 newrelic-vault $region $method $vault_path/$k value=$v
}

function _getVaultData() {
  method=$1
  vault_path=$2
  default_region="us"
  region="${NRV_REGION:-$default_region}"

  if [[ $NRV_DEBUG ]]; then
    echo {method:$1, region: $region, vault_path: $vault_path}
  fi

 newrelic-vault $region $method $vault_path
}

function set() {
  vault_path=$1
  k=$2
  v=$3
  _setVaultData 'write' $1 $2 $3 2> /dev/null
  return
}

function get() {
  _getVaultData 'read' $1 2> /dev/null
  if [ $? -ne 0 ]; then
    _list $1
  fi
  return
}

function _list() {
  _getVaultData 'list' $1
}

function _vaultLogin() {
  if command -v newrelic-vault > /dev/null; then
    newrelic-vault us login -method=oidc
  fi
}

function _vaultCheckConnection() {
  echo -e "...Checking connection\n"
  newrelic-vault us list /discovery &> /dev/null
  if [ $? -eq 0 ]; then
    echo "SUCCESS"
    return 0
  else
    echo "FAILURE"
    return 1
  fi
}

NRVault() {
  # default env values
  NRV_DEBUG=
  NRV_REGION=

  # GNU getopt
  args=`getopt -n NRVault-util -o hvr: -o ls: -l check-connection -- "$*"`
  if [ $# -eq 0 ]; then
    _vaultCheckConnection
    if [ $? -ne 0 ]; then
      echo "Attempting to log in"
      _vaultLogin
    elif [ $? -eq 0 ]; then
      echo "Connected"
    fi

  fi

  while true; do
    case "$1" in
    -h|--help|?)
      _usage
      return
    ;;
    -v)
      NRV_DEBUG=1
    ;;
    -r)
      NRV_REGION=$2
      shift
    ;;
    -cc|--check-connection)
      _vaultCheckConnection
      return
      ;;
    'read')
      echo -e "method 'read' has been depricated please use 'ls'\n"
      get $2
      return
      ;;
    'ls')
      if [ $# -lt 2 ]; then
        echo 'error'
      fi
      get $2
      return
      ;;
    'write')
      if [ $# -lt 4 ]; then
        echo 'error'
      fi
      set $2 $3 $4
      return
      ;;
    'delete')
      echo "This feature is not yet supported; please use newrelic-vault to delete items from the vault."
      return
    ;;
    *)
    return
    ;;
    esac
    shift
  done
}

export -f NRVault
alias nrvana=NRVault
