#!/bin/sh
[[ -f /usr/share/git/completion/git-prompt.sh ]] && source /usr/share/git/completion/git-prompt.sh

use_color=true

if ${use_color} ; then
    RESET="\e[m";
    BLUE="\e[1;34m\]";
    GREY="\e[2;37m\]";
    COLOR1="\e[0;33m\]"
  if [[ ${EUID} == 0 ]] ; then
    # root
    CURRENT_PATH="$GREY\w$RESET";
    COMPNAME="$RESET$BLUE\h$RESET";
    GIT_INFO="\$(__git_ps1 '|$COLOR1%s$RESET')";
    END=" \$ ";

    PS1="\e[31;40m❲u@\h❳\e[0m \w \e[0m\n \$ "
  else

    CURRENT_PATH="$GREY\w$RESET";
    COMPNAME="$RESET$BLUE\h$RESET";
    GIT_INFO="\$(__git_ps1 '|$COLOR1%s$RESET')";
    END=" \$ ";

    PS1="❲$COMPNAME$GIT_INFO❳ $CURRENT_PATH\n$END"
  fi
else
    if [[ ${EUID} == 0 ]] ; then
      # show root@ when we don't have colors
      PS1='\u@\h \W \$ '
    else
      PS1='\u@\h \w \$ '
    fi
fi
