live_config_reload = true

[cursor]
blink_interval = 750
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Always"
shape = "Block"

[scrolling]
history = 10000

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[shell]
args = ["-l"]
program = "/bin/bash"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = false
opacity = 0.95
# history = 10000
title = ""

[window.dimensions]
columns = 106
lines = 26

[window.padding]
x = 1
y = 0
